#!/bin/sh
APPNAME=noble
PREFIX=/usr/local/bin
TOPDIR="$PREFIX"/truetouch/qml/BlueTooth/"$APPNAME"
BINDIR="$TOPDIR"/build/Release
TMPDIR=debian/tmp

echo "chmod u+s "$BINDIR"/hci-ble"
chmod u+sx "$BINDIR"/hci-ble

echo "chmod u+s "$BINDIR"/l2cap-ble"
chmod u+sx "$BINDIR"/l2cap-ble
